[[main]]
  name = "What we do"
  pageRef = "services"
  weight = 10
[[main]]
  name = "Work"
  pageRef = "work"
  weight = 20
[[main]]
  name = "Expertise"
  pageRef = "expertise"
  weight = 30
[[main]]
  name = "About"
  pageRef = "about"
  weight = 50
