colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true

enableA11y = true
enableSearch = true
enableCodeCopy = false
enableStructuredBreadcrumbs = false

mainSections = ["writing", "work"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "landing"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/writing/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = false
  showViews = false
  showLikes = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showReadingProgress = false
  showTableOfContents = false
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = ["linkedin", "email"]
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = false
